export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const API_ERROR = "LOGIN_API_ERROR";

export const LOGIN_WITH_AZURE = "LOGIN_WITH_AZURE";
export const LOGIN_WITH_AZURE_SUCCESS = "LOGIN_WITH_AZURE_SUCCESS";
export const LOGIN_WITH_AZURE_ERROR = "LOGIN_WITH_AZURE_ERROR";

export const AZURE_LOGIN = "AZURE_LOGIN_RESPONSE";
export const AZURE_LOGIN_SUCCESS = "AZURE_LOGIN_SUCCESS";
export const AZURE_LOGIN_ERROR = "AZURE_LOGIN_ERROR";

export const VERIFY_EMAIL = "VERIFY_EMAIL";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_ERROR = "VERIFY_EMAIL_ERROR";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

export const CLEAR_AUTH_RESPONSE = "CLEAR_AUTH_RESPONSE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
