/* GET INVOICES */
export const GET_INVOICES = "GET_INVOICES";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL";

/* GET SPECIFIC INVOICE */
export const GET_SPECIFIC_INVOICE = "GET_SPECIFIC_INVOICE";
export const GET_SPECIFIC_INVOICE_SUCCESS = "GET_SPECIFIC_INVOICE_SUCCESS";
export const GET_SPECIFIC_INVOICE_FAIL = "GET_SPECIFIC_INVOICE_FAIL";
