/* GET INVOICES */
export const GET_INVOICES = "GET_INVOICES";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL";

/* GET SPECIFIC INVOICE */
export const GET_SPECIFIC_INVOICE = "GET_SPECIFIC_INVOICE";
export const GET_SPECIFIC_INVOICE_SUCCESS = "GET_SPECIFIC_INVOICE_SUCCESS";
export const GET_SPECIFIC_INVOICE_FAIL = "GET_SPECIFIC_INVOICE_FAIL";

export const GET_CREDIT_CARD_INFO = "GET_CREDIT_CARD_INFO";
export const GET_CREDIT_CARD_INFO_SUCCESS = "GET_CREDIT_CARD_INFO_SUCCESS";
export const GET_CREDIT_CARD_INFO_FAIL = "GET_CREDIT_CARD_INFO_FAIL";

export const GET_BANK_ACCOUNT_INFO = "GET_BANK_ACCOUNT_INFO";
export const GET_BANK_ACCOUNT_INFO_SUCCESS = "GET_BANK_ACCOUNT_INFO_SUCCESS";
export const GET_BANK_ACCOUNT_INFO_FAIL = "GET_BANK_ACCOUNT_INFO_FAIL";

export const CREATE_PAYMENT_JOURNAL = "CREATE_PAYMENT_JOURNAL";
export const CREATE_PAYMENT_JOURNAL_SUCCESS = "CREATE_PAYMENT_JOURNAL_SUCCESS";
export const CREATE_PAYMENT_JOURNAL_FAIL = "CREATE_PAYMENT_JOURNAL_FAIL";

export const ADD_BANK_ACCOUNT = "ADD_BANK_ACCOUNT";
export const ADD_BANK_ACCOUNT_SUCCESS = "ADD_BANK_ACCOUNT_SUCCESS";
export const ADD_BANK_ACCOUNT_FAIL = "ADD_BANK_ACCOUNT_FAIL";

export const ADD_CREDIT_CARD = "ADD_CREDIT_CARD";
export const ADD_CREDIT_CARD_SUCCESS = "ADD_CREDIT_CARD_SUCCESS";
export const ADD_CREDIT_CARD_FAIL = "ADD_CREDIT_CARD_FAIL";

export const GET_AVAILABLE_CARDS = "GET_AVAILABLE_CARDS";
export const GET_AVAILABLE_CARDS_SUCCESS = "GET_AVAILABLE_CARDS_SUCCESS";
export const GET_AVAILABLE_CARDS_FAIL = "GET_AVAILABLE_CARDS_FAIL";
